### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by Vweber73** [vc64web/virtualc64web#164]
The sound persists (although it hangs on the same note) when you suspend the app, it is systematic, it happens every time with every game or demo.

In a snapshot of fighter pilot while being in the aircraft, and same thing, when I load it, the reactor sound is gone, although it is back as soon as I press Q or A to modify the thrust.

**Comment by mithrendal** [comment]
could try to switch to the modern sound interface ... the default is still the old deprecated sound interface 

go to settings and select `render audio in separate thread` this will use the modern new sound interface ... vAmigaWeb only uses this new sound interface 

hope fully this will fix it...

**Comment by Vweber73** [comment]
This worked fine for the "app suspended" issue, thanks !
It did nothing for the "no sound when restoring a snapshot" issuew though.

**Comment by mithrendal** [comment]
>This worked fine for the "app suspended" issue, thanks !

cool seems we should set the default to the modern sound interface see also #146 ... older devices as the iphone 5s are stuck at iOS 12 and therefore only have the old interface ... but maybe its time to move on and cut the support of these ancient devices ?

>It did nothing for the "no sound when restoring a snapshot" issuew though.

I reproduced it too ... strangely it is only this game which exhibits this issue ... probably has something to do with the SID waveforms which has to be reinitialised ... I tried other sampling methods of resid with the same effect ... when it is only fighterpilot then maybe we just leave it as it is what do you think?... when other titles too show this issue we have to probably check the Mac version and open an issue in the original virtualC64 for mac of @dirkwhoffmann

**Comment by Vweber73** [comment]
Yes, well it is not critical... Maybe it would happen with other flight simulators throwing a constant sound of reactors...
Cheers

**Comment by mithrendal** [comment]
It could be that the current sid state is not saved correctly but when the next tone comes it is already irrelevant and the mute effect disappears … well flight simulators with a constant noise could be most affected to this

**Comment by mithrendal** [comment]
very good find but not easy to fix due to the external Resid Sound lib which is used for sound generation
