### ISSUE TITLE
Status bars on Android

### ISSUE THREAD

**Issue by Vweber73** [vc64web/virtualc64web#165]
The status bars (top and bottom) are always shown. Great if it could be configurable, and for vAmiga (which has the opposite setting, both bars hidden) as well !

**Comment by mithrendal** [comment]
just for reference ... I found this when I searched for how to programmatically change the display setting in a PWA https://stackoverflow.com/questions/53048372/how-to-programmatically-switch-display-from-standalone-to-fullscreen-in-pwa

**Comment by mithrendal** [comment]
display size has been changed in the manifest to fullscreen which hides the bottom status bar on reinstall
