### ISSUE TITLE
No sound on iPad with Summer Games

### ISSUE THREAD

**Issue by ChristianWeyer** [vc64web/virtualc64web#167]
When using https://vc64web.github.io/ on my iPad with iOS 15.5 and running Summer Games (https://csdb.dk/release/?id=206601), I do get no sound at all.
This d64 works fine on Safari on my MacbookPro, though.

Any ideas on what could be the issue here?

**Comment by mithrendal** [comment]
Hi @ChristianWeyer 

just checked it on my iPhone 6s also iOS 15.5

I think most likely your iPad is muted ... do other titles work well ? 

also check whether you are in warp mode ... when warping during disk load sound will be shut off ... 

are you using main thread audio rendering in the settings ? This is already deprecated by modern browsers ... try selecting audio rendering in separate thread ...

**Comment by ChristianWeyer** [comment]
OMG. It was muted 🤦🏼‍♂️. Strange, I could hear sound in other apps...
Thanks for the quick reply!

**Comment by mithrendal** [comment]
👍🏻 Happened also more than once to me.
