### ISSUE TITLE
Running C64-Cursor on iPad/Safari 

### ISSUE THREAD

**Issue by ha24-1** [vc64web/virtualc64web#182]
Hi, sometimes I´m using virtual or physical keyboard on vc64web on my iPadPro 2020 (iPadOS 16.3).
When I swipe to another app and return to vc64web the c64-cursor runs through all lines - like I pressed SPACE for long time. No way to stop this (except re-start vc64web).
No problem with changing to another app and return when virtual keyboard is off or no physical kb is connected.

I found out this behaviour is on Chrome and Safari (ahh! :-) ) only - not when using Firefox.

Can anyone confirm this issue?

Thank you and best regards!

**Comment by mithrendal** [comment]
Confirmed ... when pressing a key and switching the app into background the key release event will get lost ... consequently when returning to the vc64web.app it thinks key is still pressed down...

I have to evaluate how to deal with it... when it happens to you the just press and release the same key again and the key in question should be released and everything should be normal again ...

Solution I can think of is reacting to the app in foreground event and then reset the keyboard ... this would fix the issue right?

**Comment by mithrendal** [comment]
@ha24-1  fixed 😎...  I am resetting the keyboard of the c64 when the app is sent to background and when it is reactivated again ...

can you test it ?

**Comment by ha24-1** [comment]
@mithrendal: thank you for your message! I tested it again but unfortunately the cursor runs through the screen as reported couple of weeks ago. 
I resetted Safari on iPad, so a completely new version of vc64 should be downloaded/ used?
Sending vc64 into background will be done with a wipe from lower edge of the display upwards - unfortunately at same position is the space bar of virtual keyboard. maybe a little space between edge an keyboard could fix this (a hack, I admit... )
But - normally I'm using a physical keyboard on iPad - here it works. So, don't worry... :-)

**Comment by mithrendal** [comment]
It is definitely fixed … I just retested with a physical keyboard on iPhone… I think you tested still the previous not yet updated version which had the keyboard problem

Please go to settings and click on `update installation manually` … running vc64web in safari is not optimal … better you install it as a stand alone app on your homescreen …you can do this with the `safari share button`  and then choose `add to homescreen`.

Let me know whether it works for you …

**Comment by ha24-1** [comment]
Sorry for delayed answer: switch to „keycap touch behaviour = smartphone like“ fixed it for me on ipad Pro 11“. Thank you!
Another „issue“: when virtual keyboard is active and iPad is in horizonal position, you cannot see C64s cursor in lower screen rows - sorry,  no idea, how to fix this… ;-)
