### ISSUE TITLE
cannot start D64 when building with latest emsdk

### ISSUE THREAD

**Issue by fieserWolF** [vc64web/virtualc64web#185]
While starting PRGs run fine on my server, I cannot run D64.

This is what I have done:
1. I have inserted all four original ROMs first.
2. file slot: selected my .D64
3. X auto load / X auto run -> Insert Disk
4. repeating window with this error message pops up: Error: index out of bounds

When I try this on your server at https://vc64web.github.io/ is works fine. What could be wrong?

**Comment by mithrendal** [comment]
confirmed with `emsdk 3.1.27` 

I am just doing a downgrade with

`emsdk install 3.1.15`  that is the one used to compile the current deployment on https://vc64web.github.io

from the logs I could see index out of bounds and memory problems ...

my guess they at emscripten toolchain changed something with the STACK SIZE setting as the disk is passed via stack parameter and should not be too small ...

**Comment by mithrendal** [comment]
Ok it runs perfect with `emsdk 3.1.15` ... now lets dive into their change log  ( https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md )  and see if we can spot something regarding stack size ...

**Comment by mithrendal** [comment]
found this ...

_3.1.27 - 11/29/22
The default STACK_SIZE was `reduced `from `5MB` to `64KB`. Projects that use more than 64Kb of stack will now need specify -sSTACK_SIZE at link time. For example, -sSTACK_SIZE=5MB can be used to restore the previous behaviour._ 

will reinstall latest emsdk and add linker flag as they suggest i.e. `-sSTACK_SIZE=5MB`

**Comment by mithrendal** [comment]
works here with `-STACK_SIZE=5MB` and `emsdk 3.1.31` 😎


<img width="809" alt="image" src="https://user-images.githubusercontent.com/17108995/216814263-8ce3e1de-e456-4b9d-8590-897ddbcde0a2.png">

**Comment by fieserWolF** [comment]
Yeah, works like a charm now. Thanks a lot!
