### ISSUE TITLE
How does one drag a link from csdb.dk into the drop zone?

### ISSUE THREAD

**Issue by gooddosh** [vc64web/virtualc64web#208]
Do I have to create a webloc file and drag it in? I wish I could just paste a URL, but I'm probably missing something very easy.

**Comment by mithrendal** [comment]
There are two different csdb.dk website items which you can drag into the vc64web screen space. These are `titles` and `downloads`.

### lets try `titles`

drag title from a search result into vc64web

<img width="1174" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/d2d43dd0-b694-4afa-ad17-003286dfff7c">

grab the search title directly onto the vc64web screen and it opens it inside its own csdb.dk browser component. from where you can start it by pressing the blue button at the bottom.

see here

<img width="1174" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/e91c69a9-2c6a-4ab7-ba33-7c7c22a21330">



### then there are `Downloads` 

when you go into the http://csdb.dk detail view you can drag a link to the program into the vc64web screen which then tries to mount and start it

<img width="1174" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/2234d6db-8b8d-4296-8da0-3b9426e0e3c9">


here you see that the dragged download link to the .prg file has started upon landing inside the vc64web screen

<img width="1174" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/40ce732d-45d2-46e8-b4ff-995c981c636d">

**Comment by mithrendal** [comment]
>I wish I could just paste a URL

there is also a third way of external feeding it via the user interface 

pasting a `release link` into vc64web's csdb search text field

e.g. https://csdb.dk/release/?id=139278

<img width="1191" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/04dc4815-fa4c-4cfd-9eec-62ba659076ed">

**Comment by gooddosh** [comment]
Thank you. What options are available on an iPhone (same question)?

**Comment by mithrendal** [comment]
on iPhone dragging media from csdb.dk into the vc64web works too. 🤓

1.  open vc64web from home screen to be sure it is already there when we want to drop c64 disk files
2. switch to safari app
3.  go to the csdb website where you see e.g. a .d64 or .prg file
4. press on that file and hold until it pops out and becomes an overlay
5. now while finger is still holding that file leave with another finger the app and switch to vc64web
6. the file which still is dragged by the first finger shows now a green circle with a + icon.
7. now let the first finger drop that csdb .d64 file link i.e. lift of the first finger from the touch display


although that works somehow I think one is better suited with the vc64web's internal csdb search function... no?
