### ISSUE TITLE
Touch controls in iPhone Part2

### ISSUE THREAD

**Issue by mithrendal** [vc64web/virtualc64web#213]
this is part 2 of the touch joystick story https://github.com/vc64web/virtualc64web/issues/207 … 

the plan is to implement the following settings 
`
virtual joystick = ` `base moves`, `base fixed on first touch`, `stationary` 
`dead zone` = 0,8,12,16,24 (defaults to 12)

**Comment by mithrendal** [comment]
new settings in place 🤓

<img width="840" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/831fbacf-743b-44b2-bee5-7c8511505f40">


here are the different joystick types 

<img width="840" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/9887ac97-6616-454f-8bb9-1fdcba3b771b">


dead zone is also ready for prime time...

deployed to https://vc64web.github.io


next I will look into the occasionally freezing joystick issue

**Comment by gooddosh** [comment]
Getting very close now...

virtual joystick = base moves, base fixed on first touch, stationary: needs to be at least 5pix from the corner.
dead zone = 0,8,12,16,24 (defaults to 12): prefer 14, recommend 0,8,12,14,16...

**Comment by mithrendal** [comment]
roger… 14 and 5px added

![IMG_0344](https://github.com/vc64web/virtualc64web/assets/17108995/8da4a397-6808-4456-887e-30e1ed21f035)


on iPad stationary is too far on the bottom I think… what about the middle?

**Comment by mithrendal** [comment]
or we add three stationary positions?

virtual joystick =  `base moves`, `base fixed on first touch`, `stationary top` , `stationary middle` ,`stationary bottom`,

**Comment by gooddosh** [comment]
Prefer side-middle as well. Oh, all options, middle = default. Nice!

**Comment by gooddosh** [comment]
Further in though. 5pix was a minimum. I'd say 10 or 20.

**Comment by mithrendal** [comment]
I have changed how the touch start is processed. Before the change the code ignored other touches when a touch is already in progress (touch down, move, end) ... this led in some occasion to freezes e.g. when an incoming call interrupted the touch live cycle it seems that it never got the touch end and therefore did not accept any new touch events and therefore was frozen.


now the new code handles it different ... whenever a new touch is detected and the old was not finished then the new touch will take over the virtual fire or joystick controller.

pushed to https://vc64web.github.io

**Comment by mithrendal** [comment]
added `stationary bottom` and `stationary middle` types...

top position is not needed me thinks...

gave the bottom position a larger margin so that it does not trigger accidentally the iPhoneOS/iPadOS swipe up gesture.

I think it is now complete ... I will port this stuff over to vAmigaWeb now

**Comment by gooddosh** [comment]
OK, I now LOVE "base fixed on first touch" when set to 14 (recommend that for default). That issue is squashed, and I can really play now. In the CLI, I am seeing characters generated for virtual joystick #1 port only. So, seems like it's leaking extra data, unless the original C64 did that, and I don't recall it.

Regarding the permanently stationary joystick, I think it's good to have it, though I now prefer the one mentioned above (brilliant solution, by the way). But I think the stationary joystick should have a bigger margin. Whatever it's set at now, push it in and up another 10 or 20 pixels. It's too far out of the way to be comfortable to use.

I think the "base fixed on first touch" mode makes this an incredible mobile gaming platform. I'm truly thrilled with it. I think, with renewed practice, I could get a perfect score in Choplifter without using a physical joystick.

**Comment by mithrendal** [comment]
thank you a lot @gooddosh for your overall input on the joystick … it was invaluable …  I would have never know that something like a dead or rest zone even existed on a virtual joystick…😅 and that it made such a difference …  after my „real regular work“ I will increase the left margin of the stationaries to something bigger like 25 or so

>In the CLI, I am seeing characters generated for virtual joystick https://github.com/vc64web/virtualc64web/issues/1 port only. So, seems like it's leaking extra data, unless the original C64 did that, and I don't recall it.

the real machine also does this ... it is the correct behaviour 😉

>14 (recommend that for default)

it is as you suggested...

and vAmigaWeb has the same joystick settings now too ! Thanks a lot for this again.

**Comment by gooddosh** [comment]
Honor is mine. I've never worked with a more responsive developer. The final virtual joystick is cutting-edge. While I can't be quite as competitive as with a real one, I think it's now the best virtual one I've used. Well done!

**Comment by mithrendal** [comment]
left margin of stationary is now 60pixel when there is enough screen space...  when a smaller iPhone is in portrait mode where the horizontal width is much smaller than in landscape then the margin is computed from the (half of the width - joystick base width) / 2 ... otherwise the base would go into the fire zone on the smaller iPhones.
