### ISSUE TITLE
Touch example crashes on touch devices

### ISSUE THREAD

**Issue by JesperJuul** [vc64web/virtualc64web#224]
It looks like recent versions have a bug in the touch code? 

If I run https://vc64web.github.io/doc/wiki/player_example2.html either on my phone (Firefox or Chrome) or in Chrome for Windows, selecting developer tools and emulating a phone layout, I get the following error:

vc64_ui.js:3838 Uncaught ReferenceError: stationaryBase is not defined
    at register_v_joystick (vc64_ui.js:3838:29)

The emulator just shows "Exception thrown, see JavaScript console".

I tried defining stationaryBase, but that leads to a new error:

virtualjoystick.js:30 Uncaught ReferenceError: current_vjoy_touch is not defined
    at new VirtualJoystick (virtualjoystick.js:30:14)

Thank you for the great work.

**Comment by mithrendal** [comment]
confirmed:
touch control in general is working when invoking the stand alone version at https://vc64web.github.io

when embedding vc64web in another web page, enabling virtual touch joystick then it crashes 🙈 ... investigating now

**Comment by mithrendal** [comment]
I think it is fixed now 🤓

@JesperJuul thanks for reporting

**Comment by JesperJuul** [comment]
Amazing, thank you @mithrendal!
