### ISSUE TITLE
Unable to select c64 roms on iOS

### ISSUE THREAD

**Issue by DkWeb** [vc64web/virtualc64web#226]
I have installed the app to my homescreen on my iPhone but I'm unable to "install" a custom rom. But I can choose to install the open roms without a problem.

After clicking on a certain rom slot within the settings dialog (e.g. "basic rom") I can choose a file from the file system, but it does never appear within the slot. There is no iOS dialog asking me for permitting the access to the filesystem, so maybe there is a problem with the rights the app is asking for?

Some basic environment information:
iPhone 12
iOS: 16.7.2

**Comment by mithrendal** [comment]
Hi @DkWeb 
The emulator welcomes you with a dialog where you can choose any of the C64 compatible system ROMs stored on your iPad/iPhone , e.g. original Commodore Roms, or SpeedDOS, DolphinDOS, … (you find these files inside various other emulators like Denise or Vice (e.g. in [official vice sources](https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/data) under folder c64 they are called kernal-901227-03.bin, basic.bin and chargen.bin, and in folder Drives you want some 1541.bin)

let me check whether the file extension has to be .bin ...

**Comment by DkWeb** [comment]
Hi and thanks a lot for the quick and response and thorough explanation. You've leat me to the solution: I've dropped the roms via airdrop from my mac to the iPhone and  unfortunately the files were messed up by that. Maybe it is a bit unfortunate, that no error message is displayed,  but that is surely not a bug :-).
