### ISSUE TITLE
Datasette STOP and PLAY

### ISSUE THREAD

**Issue by vari77** [vc64web/virtualc64web#230]
Good morning, congratulations for the splendid emulator that allows me to use my iPad to bring the C64 back to life. I encountered a problem that I couldn't solve, a program on cassette requires me to press the STOP button on the DATASETTE, but I don't know where it is. Is there the possibility of emulating the PLAY and STOP buttons of the DATASETTE?
I tried to see if I could create the button with "defining actions" but I couldn't find how to insert it.

**Comment by mithrendal** [comment]
Confirmed datasette stop is missing…😬

I will implement convenient datasette play and stop actions later today …

**Comment by vari77** [comment]
Great, I can't wait to try these new features. Thank you

**Comment by mithrendal** [comment]
new actions have been added, namely `datasette_play` `datasette_stop` `datasette_rewind`

I created for my setup three global action buttons as seen here

<img width="1206" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/9aa86cac-4fb3-436b-be2d-24faaa384d2d">


you can just type them or choose them from `system actions`

<img width="797" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/7ad86c86-a7e8-4ec9-ad3a-57095c4f5d9b">


hope it works for you now... 

BTW: vc64web on iPad feels best when installed to homescreen as a regular web app.

**Comment by vari77** [comment]
Thanks @mithrendal, it works correctly now. :-)
I'm already using it as a web app, hoping that Apple doesn't block this possibility in the future.

**Comment by mithrendal** [comment]
>Thanks @mithrendal, it works correctly now. :-)

very good 😎... I will close this issue then as completed
