### ISSUE TITLE
NTSC support

### ISSUE THREAD

**Issue by ejelly** [vc64web/virtualc64web#239]
It would be great if the emulator had NTSC support.

**Comment by mithrendal** [comment]
Hi,
first the virtualC64 emulation core which is used by vc64web has basically a NTSC support. 😎

![image](https://github.com/vc64web/virtualc64web/assets/17108995/88a90e55-6a2c-477d-8e94-711dcfbc4fd1)

why would one like to use that ? 🤔

use case A: run NTSC titles
use case B: get butter smooth scrolling on 60Hz displays (vsync)

discussion:
we can easily get case B **without** using NTSC VICII modes at all by just  running the system around 20 % faster in vsync mode. i.e. every host frame triggers exactly one c64 frame. 😊

on the other hand we can also make the  NTSC VICII modes configurable in the vc64web settings but for compatibility reasons have also a look to here https://github.com/dirkwhoffmann/virtualc64/issues/754

**Comment by ejelly** [comment]
I’d like to use Flight Simulator II though, and that really only works properly with NTSC. Then there’s of course other games and demos.

North Americans (for example) will also be more familiar with the aspect ratio and differing border scanline count of NTSC C64s.

**Comment by ejelly** [comment]
Oh, I see now. Looks like Virtual C64 doesn’t really support NTSC, that of course affects this project as well, yeah. 

Pity, because FS2 is really still worth using today. It has a certain challenge, and great charm with its many, many scenery disks.

**Comment by mithrendal** [comment]
>Pity, because FS2 is really still worth using today. It has a certain challenge, and great charm with its many, many scenery disks.

have you already tried in VirtualC64 for mac ?


lets try with the NTSC VICII 8562

<img width="878" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/1023825a-831e-4b6d-90d0-585cb5ff08c2">

ok I can see the aspect ratio and borderscan lines are now different with this VICII model.


now I am in flight II

<img width="878" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/d2238c6a-7ea3-40d9-82ae-6b4c45b1faae">

<img width="878" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/8edeaeaf-46ef-4a2f-bb77-c1c83d66d937">

I see the instruments are oval instead in NTSC of circles in PAL.

**Comment by dirkwhoffmann** [comment]
VirtualC64 does have real NTSC support (simply select the proper VICII revision). However, NTSC is not as compatible as PAL. Most titles will work, but not all. I didn't spend as much dev time on NTSC modes as on PAL modes, as most C64 titles have been made for the PAL market back in the day.

**Comment by mithrendal** [comment]
>VirtualC64 does have real NTSC support (simply select the proper VICII revision). 

👍 nice ! Good to know, then I just use that API to switch between NTSC and PAL... working on it right now...

**Comment by mithrendal** [comment]
status update

I am able to switch between NTSC and PAL without any reset...

<img width="1089" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/41abe0a7-796d-48d9-89b8-e51b29293998">


<img width="1089" alt="image" src="https://github.com/vc64web/virtualc64web/assets/17108995/1249998d-6e89-4015-9637-a009f46a5f19">

in NTSC mode it renders 60 frames per second and in PAL 50 frames.

😎

**Comment by ejelly** [comment]
Sweet! Yeah, there are a few details different between PAL and NTSC devices.

**Comment by mithrendal** [comment]
I will do some more testing and code cleanup… but I would say that you can expect an NTSC update in the coming days if test results are ok…

**Comment by mithrendal** [comment]
it is online .... https//vc64web.github.io supports now switching between different NTSC / PAL VIC-II revisions. 😎

should we also add a setting to enable the gray dot bug, or switching  between different revisions of the CIAs ?

**Comment by gooddosh** [comment]
Outstanding!

**Comment by mithrendal** [comment]
😬 I forgot to update the value of the vic rev in the settings dialog when restoring from a snapshot ... 

fixed and published 😎

**Comment by mithrendal** [comment]
@ejelly as NTSC VIC2s are now supported I will close the issue... if anything is wrong with it just reopen

**Comment by ejelly** [comment]
Thanks a lot, that is great!

By the way, as far as I know (I grew up with a PAL C64 as well, but FS2 doesn't exist for that), NTSC affects more than just speed and aspect ratio. As far as I could tell, FS2's physics are noticeably "wrong" on a PAL C64. It's not just that speed, gravity etc. are scaled, rather the plane seems generally less stable on PAL C64s, as stable states (attitude, power etc.) on NTSC don't seem stable on PAL. I could not even find any other stable states on PAL, most likely because the original author only made their software playable for NTSC.

My guess is that the physics are calculated in some or all of horizontal retrace, vertical retrace, and timer interrupt-driven code, and the differing line count and maybe even different relative timing between timer interrupts and retrace code breaks some hardcoded assumptions of the physics steps calculations.

With sophisticated demos using cycle counting it should be much worse, as it will be off completely. Not that I could find many NTSC demos to begin with...
