### ISSUE TITLE
keyboard mapping

### ISSUE THREAD

**Issue by mithrendal** [vc64web/virtualc64web#28]
1.  F1 to F8 are not correctly mapped (only iOS, on a mac this works correctly)
2. on a german keyboard Z and Y are swapped ...

**Comment by mithrendal** [comment]
test result mac german keyboard ....
![grafik](https://user-images.githubusercontent.com/17108995/83678558-3775a100-a5de-11ea-9b1f-70f0023b89a0.png)

gray keys are not yet reachable ... that is you can not type them by any combination of keys ... effectively unmapped🙊

**Comment by mithrendal** [comment]
virtualc64web test result iOS safari german keyboard (brand: Anker....)


![DA8E83A6-1FF7-4148-A275-54D2013BBFB3](https://user-images.githubusercontent.com/17108995/83679540-d9e25400-a5df-11ea-9ded-41dddc97b8c9.png)

**Comment by dirkwhoffmann** [comment]
VirtualC64web needs a virtual keyboard 😎.

**Comment by mithrendal** [comment]
yes I see it too

**Comment by mithrendal** [comment]
there are some on the web ...

this one is huge ... too big for my taste ...
https://mottie.github.io/Keyboard/

this tiny one here is nice ... maybe a candidate ?
https://github.com/mBut/jquery.mlkeyboard/

or we can do on our own one ...

**Comment by dirkwhoffmann** [comment]
> this tiny one here is nice ... maybe a candidate ?

Yes, that one is very nice 🥰. Hopefully, it's easy to change it into a C64 keyboard, but I guess the code isn't too complicated.

**Comment by mithrendal** [comment]
I played with some virtual keyboards. Some are nice. Based on your good experience in developing an own CPU core instead of taking the musashi. I decided to develop our own keyboard now. From the ground up. The goal is the same ...it should give us the best user experience regardless which device  will be used. 🤤

**Comment by mithrendal** [comment]
![BADC3EC0-4ACC-45D2-B6E6-99FC2C8F127C](https://user-images.githubusercontent.com/17108995/83978833-5dff4900-a90a-11ea-88ea-08d0fc106a25.png)

On restore the core complains with an assertion  🙉 and stops working 

@dirkwhoffmann do you have an idea whats wrong with pressing restore?

the commodore key is still unmapped 🙈

All other keys are working with vc64webs brand new toy „the handcrafted virtual keyboard“ short HVK. 😎


On small devices (like iphone portrait mode) the keyboard turns automatically into a scrollable „touchbar“  This way the keys stay still big enough to read and type on... 

On large screens it centers automatically and scrolling is gone. 

Published to https://dirkwhoffmann.github.io/virtualc64web/

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/83979578-b7b64200-a90f-11ea-84da-7ebd027191ab.png)

the commodore key was easy ... it was just an mapping error

only left 

right shift  - how what are the correct two key codes ?
restore - gives the following
```
wasm_key ( 9, 9, 1 ) 
Assertion failed: row < 8, at: C64/Computer/Keyboard.cpp,129,pressKey
```

is the key code 9,9 wrong ? It is the second last in the following code 

```
       // Second physical key row
            [7, 2], [7, 6], [1, 1], [1, 6], [2, 1], [2, 6], [3, 1], [3, 6],
            [4, 1], [4, 6], [5, 1], [5, 6], [6, 1], [6, 6], [9, 9], [0, 5] /* f3 */,
```
I copied that code from the mac version ... and translated it into javascript ... file is vC64keymap.js

**Comment by dirkwhoffmann** [comment]
> is the key code 9,9 wrong ? It is the second last in the following code

It purposely produces an assertion failure to prevent anybody from trying to translate Restore to a key code 😅. Thing is, the restore key does not have a key code. This key is directly bound to the NMI line of the processor. You need to call a special API method to press it:

    //! @brief    Presses the restore key.
     void pressRestoreKey();

Key codes of both shift keys are here: 

    //! @brief    Checks if the shift lock key is held down.
    bool shiftLockIsHoldDown() { return shiftLock; }

    //! @brief    Checks if the left shift key is currently pressed.
    bool leftShiftIsPressed() { return keyIsPressed(1,7); }
    
    //! @brief    Checks if the right shift key is currently pressed.
    bool rightShiftIsPressed() { return keyIsPressed(6,4); }

**Comment by dirkwhoffmann** [comment]
BTW, I like the idea of implementing the virtual keyboard from ground up.

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/84070449-73d54280-a9cc-11ea-971d-c688d2de0358.png)

HVK (handcrafted virtual keyboard passed all tests now) 😎👍🏿

**Comment by mithrendal** [comment]
lets review the problems ...

problem 1: the anker bluetooth keyboard does not emit a keydown for the function keys in safari iOS
problem 2: some keys are not reachable in macOS and iOS
problem 3: keys are mapped according to their position on the 64 keyboard ... that makes Y and Z swapped



problem 1 -- one picture says it all I think
![grafik](https://user-images.githubusercontent.com/17108995/84072053-dcbdba00-a9ce-11ea-9d68-4a8be39e5493.png)

they just dont like function keys .... the virtual keyboard heals this

problem 2: see the cmd key desaster  ... the virtual keyboard heals this 

problem 3: well this one we could repair  ... should we ?

**Comment by dirkwhoffmann** [comment]
> problem 3: well this one we could repair ... should we ?

Yes, yes, yes. Having Y and Z switched is the most annoying thing in most C64 emulators.

VC64mac distinguishes between symbolic and positional key mapping. In symbolic mapping, key characters are evaluated ("Y") whereas in positional mapping, key codes are evaluated (#XXX). Symbolic mapping is more important than positional mapping (and the default in VC64mac). I think this should be supported. For everything else, there is the virtual keyboard.

**Comment by mithrendal** [comment]
I did set up a symbolic key map in vC64keymap.js, which has priority over positional mapping ... 

```
function translateKey(keycode, key)
{
    console.log('keycode='+keycode + ', key='+key);
    var mapindex;
    var sym_key = symbolic_map[key];
    if(sym_key!== undefined)
    {//if there is a symbolic mapping ... use it instead of the positional mapping
        mapindex=key_translation_map[ sym_key ];
    } 
    else
    {//when there is no symbolic mapping fall back to positional mapping
        mapindex=key_translation_map[ keycode ];
    }
    c64code=c64keymap[mapindex];
    return c64code;
}

symbolic_map = {
    z: 'KeyZ',
    y: 'KeyY'
}

```

only two keys are in it ... we could add more ... Is this the way to go ? Or do you mean a setting in a config panel which toggles between symbolic and positional mapping ?

**Comment by dirkwhoffmann** [comment]
> Is this the way to go ? 

Yes, I think this is a fruitful approach. You might want to add keys such as "!","(",")" etc. These keys need a more sophisticated translation though, because they require to press the C64 shift key as well.

**Comment by mithrendal** [comment]
Ok now I see ... when I ported  
https://github.com/dirkwhoffmann/virtualc64/blob/master/OSX/MacGUI/C64Key.swift
to javascript I wasn't carefully and rushed through it ... in order to get quick results ... so I missed out this function 


```
  // Translates a character to a list of corresponding C64 keys
    // This function is used for symbolically mapping Mac keys to C64 keys
    static func translate(char: String?) -> [C64Key] {
        
        if char == nil { return [] }
        
        switch char! {
            
        // First row of C64 keyboard
        case "ü": return [C64Key.leftArrow]
        case "1": return [C64Key.digit1]
        case "!": return [C64Key.digit1, C64Key.shift]
```

I have to carefully redo the porting of this swift class to javascript ...

**Comment by mithrendal** [comment]
I think I finished the symbolic mapping ... I ported the translate function ... Maybe it would be wise in a later version to  use the c++ version instead of porting ...
